services:
  app:
    image: music-folder-builder-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
